theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "always"
popup-border = "all"
color-modes = true
end-of-line-diagnostics = "hint"
auto-format = false

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
center = ["version-control"]
